import type { NextPage } from "next";
import Head from "next/head";
import HelloWorld from "../components/HelloWorld";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />

        <div className={styles.inner}>
          <h1 className={styles.title}>Simple, Fast, PPL</h1>

          <p className={styles.description}>
            A procedural programming language with a fast compiler
          </p>

          <div className={styles.grid}>
            <HelloWorld />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
